version: '3.8'

services:
  backend:
    build:
      context: ./docautomation_backend
      dockerfile: Dockerfile
    volumes:
      - ./docautomation_backend:/app
      - backend_static:/app/static
      - backend_media:/app/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-development-key-change-in-production
      - ALLOWED_HOSTS=localhost,127.0.0.1,backend
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://localhost:5173,http://frontend:5173
    depends_on:
      - db
    command: >
      bash -c "python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - node_modules:/app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000/api
      - VITE_DOCUMENTS_API_URL=http://localhost:8000/api/documents/
      - VITE_NLP_API_URL=http://localhost:8000/api/nlp/
      - VITE_GENERATE_API_URL=http://localhost:8000/api/generate/
      - VITE_MEDIA_URL=http://localhost:8000/media/
    depends_on:
      - backend
    command: npm run dev -- --host 0.0.0.0

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=docagent
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  backend_static:
  backend_media:
  node_modules: 