# Generated by Django 4.2.20 on 2025-03-07 15:01

from django.db import migrations, models
import django.db.models.deletion
import document_generation.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document_processing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=document_generation.models.template_file_path)),
                ('template_type', models.CharField(choices=[('docx', 'DOCX'), ('pdf', 'PDF'), ('txt', 'Text'), ('markdown', 'Markdown'), ('html', 'HTML')], default='docx', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('prompt', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to=document_generation.models.generated_document_path)),
                ('output_format', models.CharField(choices=[('docx', 'DOCX'), ('pdf', 'PDF'), ('txt', 'Text'), ('markdown', 'Markdown'), ('html', 'HTML')], default='docx', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('content', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_documents', models.ManyToManyField(blank=True, to='document_processing.document')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='document_generation.documenttemplate')),
            ],
        ),
    ]
